# Generated by Django 5.2.8 on 2025-11-21 18:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción del Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre_rol'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electrónico')),
                ('contrasena', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Contraseña (Hash)')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.rol', verbose_name='Rol del Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Mascota')),
                ('especie', models.CharField(max_length=50, verbose_name='Especie (Ej: Perro, Gato)')),
                ('raza', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raza (Opcional)')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='App.usuario', verbose_name='Dueño')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id_veterinario', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad (Ej: Cirugía, Clínica General)')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_veterinario', to='App.usuario', verbose_name='Usuario Asociado')),
            ],
            options={
                'verbose_name': 'Veterinario',
                'verbose_name_plural': 'Veterinarios',
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Atención')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(verbose_name='Tratamiento / Indicaciones')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='App.mascota', verbose_name='Mascota')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_creados', to='App.veterinario', verbose_name='Veterinario Atendió')),
            ],
            options={
                'verbose_name': 'Historial Clínico',
                'verbose_name_plural': 'Historiales Clínicos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha del Turno')),
                ('hora', models.TimeField(verbose_name='Hora del Turno')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('CANCELADO', 'Cancelado'), ('ATENDIDO', 'Atendido')], default='DISPONIBLE', max_length=20, verbose_name='Estado del Turno')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='App.mascota', verbose_name='Mascota')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_asignados', to='App.veterinario', verbose_name='Veterinario Asignado')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha', 'hora'],
                'unique_together': {('fecha', 'hora', 'veterinario')},
            },
        ),
    ]
