# Generated by Django 5.2.8 on 2025-11-26 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.CreateModel(
            name='Internacion',
            fields=[
                ('id_internacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_alta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Alta')),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('ALTA', 'Alta médica')], default='EN_CURSO', max_length=20, verbose_name='Estado')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internaciones', to='App.mascota', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Internación',
                'verbose_name_plural': 'Internaciones',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
